In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:

np.__version__

'1.21.5'

In [4]:
!pip install pandas

In [5]:
import pandas as pd

In [6]:
pd.__version__

'1.4.4'

In [8]:
np.linspace(2,20,1000)

array([ 2.        ,  2.01801802,  2.03603604,  2.05405405,  2.07207207,
        2.09009009,  2.10810811,  2.12612613,  2.14414414,  2.16216216,
        2.18018018,  2.1981982 ,  2.21621622,  2.23423423,  2.25225225,
        2.27027027,  2.28828829,  2.30630631,  2.32432432,  2.34234234,
        2.36036036,  2.37837838,  2.3963964 ,  2.41441441,  2.43243243,
        2.45045045,  2.46846847,  2.48648649,  2.5045045 ,  2.52252252,
        2.54054054,  2.55855856,  2.57657658,  2.59459459,  2.61261261,
        2.63063063,  2.64864865,  2.66666667,  2.68468468,  2.7027027 ,
        2.72072072,  2.73873874,  2.75675676,  2.77477477,  2.79279279,
        2.81081081,  2.82882883,  2.84684685,  2.86486486,  2.88288288,
        2.9009009 ,  2.91891892,  2.93693694,  2.95495495,  2.97297297,
        2.99099099,  3.00900901,  3.02702703,  3.04504505,  3.06306306,
        3.08108108,  3.0990991 ,  3.11711712,  3.13513514,  3.15315315,
        3.17117117,  3.18918919,  3.20720721,  3.22522523,  3.24

In [9]:
np.random.rand(8)

array([0.0616953 , 0.98956306, 0.45067782, 0.56777353, 0.47473229,
       0.15193375, 0.63618436, 0.56560264])

In [10]:
np.random.rand(8,8)

array([[0.97038163, 0.66102298, 0.69412945, 0.47139048, 0.30536723,
        0.47737343, 0.87034787, 0.74717742],
       [0.87725734, 0.99048443, 0.17760711, 0.72052279, 0.28563309,
        0.90326365, 0.14887202, 0.31021029],
       [0.08513812, 0.66877478, 0.28332412, 0.81363381, 0.2589768 ,
        0.94881937, 0.16617367, 0.38544708],
       [0.3726156 , 0.01467673, 0.19894617, 0.78011364, 0.89266473,
        0.18587394, 0.94008456, 0.82965231],
       [0.62258999, 0.84897093, 0.66372753, 0.03372869, 0.87665906,
        0.14483071, 0.76135884, 0.9957478 ],
       [0.43409182, 0.63359604, 0.00357893, 0.35617014, 0.62802611,
        0.20317958, 0.88211508, 0.82774891],
       [0.71376533, 0.35893643, 0.77662393, 0.73545605, 0.15770133,
        0.60237425, 0.02380824, 0.01516901],
       [0.85854985, 0.92489962, 0.92774959, 0.08347253, 0.1162752 ,
        0.30768246, 0.02555268, 0.51421936]])

In [11]:
np.random.randint(1,100)

6

In [12]:
np.random.randint(1,100)

74

In [14]:
np.random.randint(1,100,150)

array([40, 38, 92,  8, 62, 26, 21, 24,  7, 77,  5, 21, 21, 97, 89, 96, 25,
        5, 39, 53, 41, 38, 38, 18, 75, 68, 91, 66, 12, 73, 70, 50, 25,  4,
       14, 97, 26, 52, 96, 67, 24,  6, 49, 83, 55, 69, 95, 28, 19, 18, 49,
       19, 16, 22, 41, 84, 45, 99,  5, 86, 96, 17, 11, 43, 46, 95, 83, 20,
       91, 42, 59, 25,  7, 20, 13, 48, 92, 56, 56, 33, 49, 89, 13, 26, 95,
        7, 64,  4, 30, 48,  9, 63, 36,  9, 40,  4, 25, 23, 89, 89, 27, 21,
       88, 34, 17,  6, 99, 10, 55, 35, 53, 92, 21, 69, 21, 98, 10, 15, 84,
       24, 21,  9, 20, 58, 65, 42,  1, 43, 51, 34, 26, 42, 46, 71, 93, 91,
       53, 39, 60,  8, 30, 28, 33, 14, 93, 92, 18, 55, 91, 19])

In [15]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[3:4]

array([3])

In [19]:

arr= np.arange(0,11)


In [20]:
arr_copy = arr.copy()


In [21]:
arr_copy[ : ] = 100

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
!pip install matplotlib

In [26]:
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
from PIL import Image

In [28]:
rang = Image.open('alotofrang.jpeg')

FileNotFoundError: [Errno 2] No such file or directory: 'alotofrang.jpeg'